<?php
define('HOST','localhost');
define('USER','root');
define('PASS','');
define('DBNAME','GSL');
/*
define('HOST','localhost');
define('USER','id16913996_eri');
define('PASS','Y1VoSC$|1!a77X9l');
define('DBNAME','id16913996_interfaces');*/
 ?>
